In [2]:
import pandas as pd

In [4]:
data = { 'Date' : ['2025-10-16','2025-11-25','2025-12-12']}

df = pd.date_range('2025-5-16',periods=10, freq='MS')

In [6]:
df

DatetimeIndex(['2025-06-01', '2025-07-01', '2025-08-01', '2025-09-01',
               '2025-10-01', '2025-11-01', '2025-12-01', '2026-01-01',
               '2026-02-01', '2026-03-01'],
              dtype='datetime64[ns]', freq='MS')

In [8]:
pd.date_range('2025-5-16',periods=10, freq='ME')

DatetimeIndex(['2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31',
               '2026-01-31', '2026-02-28'],
              dtype='datetime64[ns]', freq='ME')

In [10]:
pd.date_range('2025-5-16',periods=10, freq='QS')

DatetimeIndex(['2025-07-01', '2025-10-01', '2026-01-01', '2026-04-01',
               '2026-07-01', '2026-10-01', '2027-01-01', '2027-04-01',
               '2027-07-01', '2027-10-01'],
              dtype='datetime64[ns]', freq='QS-JAN')

In [12]:
pd.date_range('2025-5-16',periods=10, freq='QE')

DatetimeIndex(['2025-06-30', '2025-09-30', '2025-12-31', '2026-03-31',
               '2026-06-30', '2026-09-30', '2026-12-31', '2027-03-31',
               '2027-06-30', '2027-09-30'],
              dtype='datetime64[ns]', freq='QE-DEC')

In [14]:
pd.date_range('2025-5-16',periods=10, freq='BMS')

DatetimeIndex(['2025-06-02', '2025-07-01', '2025-08-01', '2025-09-01',
               '2025-10-01', '2025-11-03', '2025-12-01', '2026-01-01',
               '2026-02-02', '2026-03-02'],
              dtype='datetime64[ns]', freq='BMS')

In [16]:
pd.date_range('2025-5-16',periods=10, freq='BME')

DatetimeIndex(['2025-05-30', '2025-06-30', '2025-07-31', '2025-08-29',
               '2025-09-30', '2025-10-31', '2025-11-28', '2025-12-31',
               '2026-01-30', '2026-02-27'],
              dtype='datetime64[ns]', freq='BME')

In [18]:
pd.date_range('2025-5-16',periods=10, freq='BQ')

/var/folders/47/w_25m_7s321dp7p21gqngcl40000gn/T/ipykernel_86235/3710402425.py:1: FutureWarning: 'BQ' is deprecated and will be removed in a future version, please use 'BQE' instead.
  pd.date_range('2025-5-16',periods=10, freq='BQ')

DatetimeIndex(['2025-06-30', '2025-09-30', '2025-12-31', '2026-03-31',
               '2026-06-30', '2026-09-30', '2026-12-31', '2027-03-31',
               '2027-06-30', '2027-09-30'],
              dtype='datetime64[ns]', freq='BQE-DEC')

In [20]:
pd.date_range('2025-5-16',periods=10, freq='BQS')

DatetimeIndex(['2025-07-01', '2025-10-01', '2026-01-01', '2026-04-01',
               '2026-07-01', '2026-10-01', '2027-01-01', '2027-04-01',
               '2027-07-01', '2027-10-01'],
              dtype='datetime64[ns]', freq='BQS-JAN')

In [22]:
pd.date_range('2025-5-16',periods=10, freq='BQE')

DatetimeIndex(['2025-06-30', '2025-09-30', '2025-12-31', '2026-03-31',
               '2026-06-30', '2026-09-30', '2026-12-31', '2027-03-31',
               '2027-06-30', '2027-09-30'],
              dtype='datetime64[ns]', freq='BQE-DEC')

In [26]:
from datetime import datetime

In [28]:
date = datetime.today()
date

datetime.datetime(2026, 3, 5, 16, 20, 48, 76760)

In [38]:
date.strftime("%Y-%m-%d")

'2026-03-05'

In [40]:
date.strftime("%y-%m-%d")

'26-03-05'

In [56]:
date.strftime("%Y-%M-%A")

'2026-20-Thursday'

In [58]:
date = pd.date_range('2023-12-06',periods=10,freq='MS')
date

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01', '2024-07-01', '2024-08-01',
               '2024-09-01', '2024-10-01'],
              dtype='datetime64[ns]', freq='MS')

In [60]:
pd.DataFrame(date,index=range(10))

           0
0 2024-01-01
1 2024-02-01
2 2024-03-01
3 2024-04-01
4 2024-05-01
5 2024-06-01
6 2024-07-01
7 2024-08-01
8 2024-09-01
9 2024-10-01

In [62]:
pd.Series(date,index=range(10))

0   2024-01-01
1   2024-02-01
2   2024-03-01
3   2024-04-01
4   2024-05-01
5   2024-06-01
6   2024-07-01
7   2024-08-01
8   2024-09-01
9   2024-10-01
dtype: datetime64[ns]

In [68]:
x = pd.Series(range(10),index=date)
x

2024-01-01    0
2024-02-01    1
2024-03-01    2
2024-04-01    3
2024-05-01    4
2024-06-01    5
2024-07-01    6
2024-08-01    7
2024-09-01    8
2024-10-01    9
Freq: MS, dtype: int64

In [86]:
x.resample('YS').sum()

2024-01-01    45
Freq: YS-JAN, dtype: int64

In [84]:
x.resample('YE').sum()

2024-12-31    45
Freq: YE-DEC, dtype: int64

In [108]:
y = pd.DataFrame(data=[1,2,3,4,5,6,7,8],
    index=pd.to_datetime(['2023-10-12','2024-10-12','2023-10-12','2024-10-12','2023-10-12','2024-10-12','2023-10-12','2024-10-12']))

y

            0
2023-10-12  1
2024-10-12  2
2023-10-12  3
2024-10-12  4
2023-10-12  5
2024-10-12  6
2023-10-12  7
2024-10-12  8

In [110]:
y.resample("ME").mean()

              0
2023-10-31  4.0
2023-11-30  NaN
2023-12-31  NaN
2024-01-31  NaN
2024-02-29  NaN
2024-03-31  NaN
2024-04-30  NaN
2024-05-31  NaN
2024-06-30  NaN
2024-07-31  NaN
2024-08-31  NaN
2024-09-30  NaN
2024-10-31  5.0

In [112]:
y.resample("ME").sum()

             0
2023-10-31  16
2023-11-30   0
2023-12-31   0
2024-01-31   0
2024-02-29   0
2024-03-31   0
2024-04-30   0
2024-05-31   0
2024-06-30   0
2024-07-31   0
2024-08-31   0
2024-09-30   0
2024-10-31  20