In [6]:
import pandas as pd

data = {
    'emp id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'full name': ['Alice Smith', 'Bob Johnson', 'Charlie Williams', 'Diana Brown', 'Ethan Jones', 'Fiona Garcia', 'George Miller', 'Hannah Davis', 'Ian Rodriguez', 'Jenna Martinez'],
    'department': ['HR', 'Engineering', 'Sales', 'HR', 'Engineering', 'Finance', 'Sales', 'Engineering', 'Finance', 'HR'],
    'hiredate': ['2021-01-15', '2021-03-10', '2021-06-22', '2021-09-01', '2022-02-28', '2022-05-19', '2022-08-11', '2023-01-05', '2023-04-30', '2023-07-17'],
    'salary': [60000, 80000, 75000, 62000, 85000, 70000, 78000, 82000, 71000, 63000]
}

df = pd.DataFrame(data)

df['hiredate'] = pd.to_datetime(df['hiredate'])

print(df)

   emp id         full name   department   hiredate  salary
0     101       Alice Smith           HR 2021-01-15   60000
1     102       Bob Johnson  Engineering 2021-03-10   80000
2     103  Charlie Williams        Sales 2021-06-22   75000
3     104       Diana Brown           HR 2021-09-01   62000
4     105       Ethan Jones  Engineering 2022-02-28   85000
5     106      Fiona Garcia      Finance 2022-05-19   70000
6     107     George Miller        Sales 2022-08-11   78000
7     108      Hannah Davis  Engineering 2023-01-05   82000
8     109     Ian Rodriguez      Finance 2023-04-30   71000
9     110    Jenna Martinez           HR 2023-07-17   63000

In [8]:
df

   emp id         full name   department   hiredate  salary
0     101       Alice Smith           HR 2021-01-15   60000
1     102       Bob Johnson  Engineering 2021-03-10   80000
2     103  Charlie Williams        Sales 2021-06-22   75000
3     104       Diana Brown           HR 2021-09-01   62000
4     105       Ethan Jones  Engineering 2022-02-28   85000
5     106      Fiona Garcia      Finance 2022-05-19   70000
6     107     George Miller        Sales 2022-08-11   78000
7     108      Hannah Davis  Engineering 2023-01-05   82000
8     109     Ian Rodriguez      Finance 2023-04-30   71000
9     110    Jenna Martinez           HR 2023-07-17   63000

In [11]:
df.groupby('department')['salary'].mean()

department
Engineering    82333.333333
Finance        70500.000000
HR             61666.666667
Sales          76500.000000
Name: salary, dtype: float64

In [13]:
df.groupby('department')['salary'].max()

department
Engineering    85000
Finance        71000
HR             63000
Sales          78000
Name: salary, dtype: int64

In [15]:
df.groupby('department')['salary'].min()

department
Engineering    80000
Finance        70000
HR             60000
Sales          75000
Name: salary, dtype: int64

In [17]:
df.groupby('department')['salary'].agg(['mean','max','min'])

                     mean    max    min
department
Engineering  82333.333333  85000  80000
Finance      70500.000000  71000  70000
HR           61666.666667  63000  60000
Sales        76500.000000  78000  75000

PIVOT Table
---

In [ ]:
df.pivot_table()

# df.pivot_table(
#     values=None,
#     index=None,
#     columns=None,
#     aggfunc: 'AggFuncType' = 'mean',
#     fill_value=None,

In [20]:
df.pivot_table(values='salary', columns='department')

department   Engineering  Finance            HR    Sales
salary      82333.333333  70500.0  61666.666667  76500.0

In [22]:
df.pivot_table(values='salary', columns='full name')

full name,Alice Smith,Bob Johnson,Charlie Williams,Diana Brown,Ethan Jones,Fiona Garcia,George Miller,Hannah Davis,Ian Rodriguez,Jenna Martinez
salary,60000.0,80000.0,75000.0,62000.0,85000.0,70000.0,78000.0,82000.0,71000.0,63000.0

In [24]:
df.pivot_table(values='salary', columns='full name',index='department')

full name,Alice Smith,Bob Johnson,Charlie Williams,Diana Brown,Ethan Jones,Fiona Garcia,George Miller,Hannah Davis,Ian Rodriguez,Jenna Martinez
department,,,,,,,,,,
Engineering,NaN,80000.0,NaN,NaN,85000.0,NaN,NaN,82000.0,NaN,NaN
Finance,NaN,NaN,NaN,NaN,NaN,70000.0,NaN,NaN,71000.0,NaN
HR,60000.0,NaN,NaN,62000.0,NaN,NaN,NaN,NaN,NaN,63000.0
Sales,NaN,NaN,75000.0,NaN,NaN,NaN,78000.0,NaN,NaN,NaN

In [26]:
df.pivot_table(values='salary', columns='full name',index='hiredate')

full name,Alice Smith,Bob Johnson,Charlie Williams,Diana Brown,Ethan Jones,Fiona Garcia,George Miller,Hannah Davis,Ian Rodriguez,Jenna Martinez
hiredate,,,,,,,,,,
2021-01-15,60000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-03-10,NaN,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-06-22,NaN,NaN,75000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-09-01,NaN,NaN,NaN,62000.0,NaN,NaN,NaN,NaN,NaN,NaN
2022-02-28,NaN,NaN,NaN,NaN,85000.0,NaN,NaN,NaN,NaN,NaN
2022-05-19,NaN,NaN,NaN,NaN,NaN,70000.0,NaN,NaN,NaN,NaN
2022-08-11,NaN,NaN,NaN,NaN,NaN,NaN,78000.0,NaN,NaN,NaN
2023-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82000.0,NaN,NaN
2023-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,71000.0,NaN
2023-07-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,63000.0

In [28]:
df.pivot_table(values='salary', columns='hiredate',index='department')

hiredate,2021-01-15,2021-03-10,2021-06-22,2021-09-01,2022-02-28,2022-05-19,2022-08-11,2023-01-05,2023-04-30,2023-07-17
department,,,,,,,,,,
Engineering,NaN,80000.0,NaN,NaN,85000.0,NaN,NaN,82000.0,NaN,NaN
Finance,NaN,NaN,NaN,NaN,NaN,70000.0,NaN,NaN,71000.0,NaN
HR,60000.0,NaN,NaN,62000.0,NaN,NaN,NaN,NaN,NaN,63000.0
Sales,NaN,NaN,75000.0,NaN,NaN,NaN,78000.0,NaN,NaN,NaN

In [30]:
df.pivot_table(values='salary', columns='hiredate',index='department', aggfunc='sum')

hiredate,2021-01-15,2021-03-10,2021-06-22,2021-09-01,2022-02-28,2022-05-19,2022-08-11,2023-01-05,2023-04-30,2023-07-17
department,,,,,,,,,,
Engineering,NaN,80000.0,NaN,NaN,85000.0,NaN,NaN,82000.0,NaN,NaN
Finance,NaN,NaN,NaN,NaN,NaN,70000.0,NaN,NaN,71000.0,NaN
HR,60000.0,NaN,NaN,62000.0,NaN,NaN,NaN,NaN,NaN,63000.0
Sales,NaN,NaN,75000.0,NaN,NaN,NaN,78000.0,NaN,NaN,NaN

In [32]:
df.pivot_table(values='salary', columns='hiredate',index='department',aggfunc='max')

hiredate,2021-01-15,2021-03-10,2021-06-22,2021-09-01,2022-02-28,2022-05-19,2022-08-11,2023-01-05,2023-04-30,2023-07-17
department,,,,,,,,,,
Engineering,NaN,80000.0,NaN,NaN,85000.0,NaN,NaN,82000.0,NaN,NaN
Finance,NaN,NaN,NaN,NaN,NaN,70000.0,NaN,NaN,71000.0,NaN
HR,60000.0,NaN,NaN,62000.0,NaN,NaN,NaN,NaN,NaN,63000.0
Sales,NaN,NaN,75000.0,NaN,NaN,NaN,78000.0,NaN,NaN,NaN

In [34]:
df.pivot_table(values='salary', columns='hiredate',index='department',aggfunc='min')

hiredate,2021-01-15,2021-03-10,2021-06-22,2021-09-01,2022-02-28,2022-05-19,2022-08-11,2023-01-05,2023-04-30,2023-07-17
department,,,,,,,,,,
Engineering,NaN,80000.0,NaN,NaN,85000.0,NaN,NaN,82000.0,NaN,NaN
Finance,NaN,NaN,NaN,NaN,NaN,70000.0,NaN,NaN,71000.0,NaN
HR,60000.0,NaN,NaN,62000.0,NaN,NaN,NaN,NaN,NaN,63000.0
Sales,NaN,NaN,75000.0,NaN,NaN,NaN,78000.0,NaN,NaN,NaN

Transform
--

In [37]:
import pandas as pd

data = {
    'emp id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'full name': ['Alice Smith', 'Bob Johnson', 'Charlie Williams', 'Diana Brown', 'Ethan Jones', 'Fiona Garcia', 'George Miller', 'Hannah Davis', 'Ian Rodriguez', 'Jenna Martinez'],
    'department': ['HR', 'Engineering', 'Sales', 'HR', 'Engineering', 'Finance', 'Sales', 'Engineering', 'Finance', 'HR'],
    'hiredate': ['2021-01-15', '2021-03-10', '2021-06-22', '2021-09-01', '2022-02-28', '2022-05-19', '2022-08-11', '2023-01-05', '2023-04-30', '2023-07-17'],
    'salary': [60000, 80000, 75000, 62000, 85000, 70000, 78000, 82000, 71000, 63000]
}

df = pd.DataFrame(data)

df['hiredate'] = pd.to_datetime(df['hiredate'])

df

   emp id         full name   department   hiredate  salary
0     101       Alice Smith           HR 2021-01-15   60000
1     102       Bob Johnson  Engineering 2021-03-10   80000
2     103  Charlie Williams        Sales 2021-06-22   75000
3     104       Diana Brown           HR 2021-09-01   62000
4     105       Ethan Jones  Engineering 2022-02-28   85000
5     106      Fiona Garcia      Finance 2022-05-19   70000
6     107     George Miller        Sales 2022-08-11   78000
7     108      Hannah Davis  Engineering 2023-01-05   82000
8     109     Ian Rodriguez      Finance 2023-04-30   71000
9     110    Jenna Martinez           HR 2023-07-17   63000

In [39]:
df.groupby('department')['salary'].max()

department
Engineering    85000
Finance        71000
HR             63000
Sales          78000
Name: salary, dtype: int64

In [41]:
df.groupby('department')['salary'].transform('max')

0    63000
1    85000
2    78000
3    63000
4    85000
5    71000
6    78000
7    85000
8    71000
9    63000
Name: salary, dtype: int64

In [47]:
df['normalization_max'] = df.groupby('department')['salary'].transform('max')

In [49]:
df

,emp id,full name,department,hiredate,salary,normalization,normalization_max
0,101,Alice Smith,HR,2021-01-15,60000,63000,63000
1,102,Bob Johnson,Engineering,2021-03-10,80000,85000,85000
2,103,Charlie Williams,Sales,2021-06-22,75000,78000,78000
3,104,Diana Brown,HR,2021-09-01,62000,63000,63000
4,105,Ethan Jones,Engineering,2022-02-28,85000,85000,85000
5,106,Fiona Garcia,Finance,2022-05-19,70000,71000,71000
6,107,George Miller,Sales,2022-08-11,78000,78000,78000
7,108,Hannah Davis,Engineering,2023-01-05,82000,85000,85000
8,109,Ian Rodriguez,Finance,2023-04-30,71000,71000,71000
9,110,Jenna Martinez,HR,2023-07-17,63000,63000,63000

In [57]:
df.drop(labels='normalization',axis=1, inplace=True)

In [59]:
df

   emp id         full name   department   hiredate  salary  normalization_max
0     101       Alice Smith           HR 2021-01-15   60000              63000
1     102       Bob Johnson  Engineering 2021-03-10   80000              85000
2     103  Charlie Williams        Sales 2021-06-22   75000              78000
3     104       Diana Brown           HR 2021-09-01   62000              63000
4     105       Ethan Jones  Engineering 2022-02-28   85000              85000
5     106      Fiona Garcia      Finance 2022-05-19   70000              71000
6     107     George Miller        Sales 2022-08-11   78000              78000
7     108      Hannah Davis  Engineering 2023-01-05   82000              85000
8     109     Ian Rodriguez      Finance 2023-04-30   71000              71000
9     110    Jenna Martinez           HR 2023-07-17   63000              63000

Pandas Data Merge, Join and Concatenation
---

In [62]:
import pandas as pd
import numpy as np

data1 = {
    'emp_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'full_name': ['Alice Smith', 'Bob Johnson', 'Charlie Williams', 'Diana Brown', 'Eve Jones', 
                  'Frank Garcia', 'Grace Miller', 'Henry Davis', 'Ivy Rodriguez', 'Jack Martinez'],
    'department': ['HR', 'Engineering', 'IT', 'HR', 'Engineering', 
                   'Sales', 'IT', 'Engineering', 'Sales', 'IT'],
    'hire_date': pd.to_datetime(['2020-01-15', '2018-03-10', '2021-06-25', '2019-11-01', '2022-04-30',
                                 '2020-08-22', '2021-09-15', '2018-05-20', '2022-01-05', '2021-03-12']),
    'salary': [60000, 80000, 75000, 62000, 81000, 
               70000, 78000, 82000, 71000, 76000]
}
df1 = pd.DataFrame(data1)
print("DataFrame 1 (df1 - Personal Info):")
print(df1)
print("-" * 50)


data2 = {
    'emp_id': [101, 102, 105, 107, 111, 112],
    'department': ['HR', 'Engineering', 'Engineering', 'IT', 'Sales', 'HR'],
    'contact_email': ['alice@comp.com', 'bob@comp.com', 'eve@comp.com', 'grace@comp.com', 
                      'new111@comp.com', 'new112@comp.com'],
    'project_code': ['P1', 'P2', 'P2', 'P3', 'P4', 'P1']
}
df2 = pd.DataFrame(data2)
print("DataFrame 2 (df2 - Contact Info):")
print(df2)
print("-" * 50)

DataFrame 1 (df1 - Personal Info):
   emp_id         full_name   department  hire_date  salary
0     101       Alice Smith           HR 2020-01-15   60000
1     102       Bob Johnson  Engineering 2018-03-10   80000
2     103  Charlie Williams           IT 2021-06-25   75000
3     104       Diana Brown           HR 2019-11-01   62000
4     105         Eve Jones  Engineering 2022-04-30   81000
5     106      Frank Garcia        Sales 2020-08-22   70000
6     107      Grace Miller           IT 2021-09-15   78000
7     108       Henry Davis  Engineering 2018-05-20   82000
8     109     Ivy Rodriguez        Sales 2022-01-05   71000
9     110     Jack Martinez           IT 2021-03-12   76000
--------------------------------------------------
DataFrame 2 (df2 - Contact Info):
   emp_id   department    contact_email project_code
0     101           HR   alice@comp.com           P1
1     102  Engineering     bob@comp.com           P2
2     105  Engineering     eve@comp.com           P2
3     107           IT   grace@comp.com           P3
4     111        Sales  new111@comp.com           P4
5     112           HR  new112@comp.com           P1
--------------------------------------------------

In [64]:
df1

   emp_id         full_name   department  hire_date  salary
0     101       Alice Smith           HR 2020-01-15   60000
1     102       Bob Johnson  Engineering 2018-03-10   80000
2     103  Charlie Williams           IT 2021-06-25   75000
3     104       Diana Brown           HR 2019-11-01   62000
4     105         Eve Jones  Engineering 2022-04-30   81000
5     106      Frank Garcia        Sales 2020-08-22   70000
6     107      Grace Miller           IT 2021-09-15   78000
7     108       Henry Davis  Engineering 2018-05-20   82000
8     109     Ivy Rodriguez        Sales 2022-01-05   71000
9     110     Jack Martinez           IT 2021-03-12   76000

In [66]:
df2

   emp_id   department    contact_email project_code
0     101           HR   alice@comp.com           P1
1     102  Engineering     bob@comp.com           P2
2     105  Engineering     eve@comp.com           P2
3     107           IT   grace@comp.com           P3
4     111        Sales  new111@comp.com           P4
5     112           HR  new112@comp.com           P1

In [68]:
pd.merge(df1,df2,on='emp_id',how='inner')

,emp_id,full_name,department_x,hire_date,salary,department_y,contact_email,project_code
0,101,Alice Smith,HR,2020-01-15,60000,HR,alice@comp.com,P1
1,102,Bob Johnson,Engineering,2018-03-10,80000,Engineering,bob@comp.com,P2
2,105,Eve Jones,Engineering,2022-04-30,81000,Engineering,eve@comp.com,P2
3,107,Grace Miller,IT,2021-09-15,78000,IT,grace@comp.com,P3

In [70]:
pd.merge(df1,df2,on='emp_id',how='left')

,emp_id,full_name,department_x,hire_date,salary,department_y,contact_email,project_code
0,101,Alice Smith,HR,2020-01-15,60000,HR,alice@comp.com,P1
1,102,Bob Johnson,Engineering,2018-03-10,80000,Engineering,bob@comp.com,P2
2,103,Charlie Williams,IT,2021-06-25,75000,NaN,NaN,NaN
3,104,Diana Brown,HR,2019-11-01,62000,NaN,NaN,NaN
4,105,Eve Jones,Engineering,2022-04-30,81000,Engineering,eve@comp.com,P2
5,106,Frank Garcia,Sales,2020-08-22,70000,NaN,NaN,NaN
6,107,Grace Miller,IT,2021-09-15,78000,IT,grace@comp.com,P3
7,108,Henry Davis,Engineering,2018-05-20,82000,NaN,NaN,NaN
8,109,Ivy Rodriguez,Sales,2022-01-05,71000,NaN,NaN,NaN
9,110,Jack Martinez,IT,2021-03-12,76000,NaN,NaN,NaN

In [72]:
pd.merge(df1,df2,on='emp_id',how='right')

,emp_id,full_name,department_x,hire_date,salary,department_y,contact_email,project_code
0,101,Alice Smith,HR,2020-01-15,60000.0,HR,alice@comp.com,P1
1,102,Bob Johnson,Engineering,2018-03-10,80000.0,Engineering,bob@comp.com,P2
2,105,Eve Jones,Engineering,2022-04-30,81000.0,Engineering,eve@comp.com,P2
3,107,Grace Miller,IT,2021-09-15,78000.0,IT,grace@comp.com,P3
4,111,NaN,NaN,NaT,NaN,Sales,new111@comp.com,P4
5,112,NaN,NaN,NaT,NaN,HR,new112@comp.com,P1

In [84]:
pd.merge(df1,df2,on='emp_id',how='outer')

,emp_id,full_name,department_x,hire_date,salary,department_y,contact_email,project_code
0,101,Alice Smith,HR,2020-01-15,60000.0,HR,alice@comp.com,P1
1,102,Bob Johnson,Engineering,2018-03-10,80000.0,Engineering,bob@comp.com,P2
2,103,Charlie Williams,IT,2021-06-25,75000.0,NaN,NaN,NaN
3,104,Diana Brown,HR,2019-11-01,62000.0,NaN,NaN,NaN
4,105,Eve Jones,Engineering,2022-04-30,81000.0,Engineering,eve@comp.com,P2
5,106,Frank Garcia,Sales,2020-08-22,70000.0,NaN,NaN,NaN
6,107,Grace Miller,IT,2021-09-15,78000.0,IT,grace@comp.com,P3
7,108,Henry Davis,Engineering,2018-05-20,82000.0,NaN,NaN,NaN
8,109,Ivy Rodriguez,Sales,2022-01-05,71000.0,NaN,NaN,NaN
9,110,Jack Martinez,IT,2021-03-12,76000.0,NaN,NaN,NaN
10,111,NaN,NaN,NaT,NaN,Sales,new111@comp.com,P4
11,112,NaN,NaN,NaT,NaN,HR,new112@comp.com,P1

In [86]:
df1, df2

(   emp_id         full_name   department  hire_date  salary
 0     101       Alice Smith           HR 2020-01-15   60000
 1     102       Bob Johnson  Engineering 2018-03-10   80000
 2     103  Charlie Williams           IT 2021-06-25   75000
 3     104       Diana Brown           HR 2019-11-01   62000
 4     105         Eve Jones  Engineering 2022-04-30   81000
 5     106      Frank Garcia        Sales 2020-08-22   70000
 6     107      Grace Miller           IT 2021-09-15   78000
 7     108       Henry Davis  Engineering 2018-05-20   82000
 8     109     Ivy Rodriguez        Sales 2022-01-05   71000
 9     110     Jack Martinez           IT 2021-03-12   76000,
    emp_id   department    contact_email project_code
 0     101           HR   alice@comp.com           P1
 1     102  Engineering     bob@comp.com           P2
 2     105  Engineering     eve@comp.com           P2
 3     107           IT   grace@comp.com           P3
 4     111        Sales  new111@comp.com           P4
 5     112           HR  new112@comp.com           P1)

In [98]:
df1.join(
    df2.set_index('emp_id'),
    on='emp_id',
    how='left',
    lsuffix='_df1',
    rsuffix='_df2'
)

,emp_id,full_name,department_df1,hire_date,salary,department_df2,contact_email,project_code
0,101,Alice Smith,HR,2020-01-15,60000,HR,alice@comp.com,P1
1,102,Bob Johnson,Engineering,2018-03-10,80000,Engineering,bob@comp.com,P2
2,103,Charlie Williams,IT,2021-06-25,75000,NaN,NaN,NaN
3,104,Diana Brown,HR,2019-11-01,62000,NaN,NaN,NaN
4,105,Eve Jones,Engineering,2022-04-30,81000,Engineering,eve@comp.com,P2
5,106,Frank Garcia,Sales,2020-08-22,70000,NaN,NaN,NaN
6,107,Grace Miller,IT,2021-09-15,78000,IT,grace@comp.com,P3
7,108,Henry Davis,Engineering,2018-05-20,82000,NaN,NaN,NaN
8,109,Ivy Rodriguez,Sales,2022-01-05,71000,NaN,NaN,NaN
9,110,Jack Martinez,IT,2021-03-12,76000,NaN,NaN,NaN

In [101]:
df1.merge(df2, on='emp_id', how='left')

,emp_id,full_name,department_x,hire_date,salary,department_y,contact_email,project_code
0,101,Alice Smith,HR,2020-01-15,60000,HR,alice@comp.com,P1
1,102,Bob Johnson,Engineering,2018-03-10,80000,Engineering,bob@comp.com,P2
2,103,Charlie Williams,IT,2021-06-25,75000,NaN,NaN,NaN
3,104,Diana Brown,HR,2019-11-01,62000,NaN,NaN,NaN
4,105,Eve Jones,Engineering,2022-04-30,81000,Engineering,eve@comp.com,P2
5,106,Frank Garcia,Sales,2020-08-22,70000,NaN,NaN,NaN
6,107,Grace Miller,IT,2021-09-15,78000,IT,grace@comp.com,P3
7,108,Henry Davis,Engineering,2018-05-20,82000,NaN,NaN,NaN
8,109,Ivy Rodriguez,Sales,2022-01-05,71000,NaN,NaN,NaN
9,110,Jack Martinez,IT,2021-03-12,76000,NaN,NaN,NaN

In [103]:
pd.concat([df1.set_index('emp_id'), df2.set_index('emp_id')], axis=1)

,full_name,department,hire_date,salary,department,contact_email,project_code
emp_id,,,,,,,
101,Alice Smith,HR,2020-01-15,60000.0,HR,alice@comp.com,P1
102,Bob Johnson,Engineering,2018-03-10,80000.0,Engineering,bob@comp.com,P2
103,Charlie Williams,IT,2021-06-25,75000.0,NaN,NaN,NaN
104,Diana Brown,HR,2019-11-01,62000.0,NaN,NaN,NaN
105,Eve Jones,Engineering,2022-04-30,81000.0,Engineering,eve@comp.com,P2
106,Frank Garcia,Sales,2020-08-22,70000.0,NaN,NaN,NaN
107,Grace Miller,IT,2021-09-15,78000.0,IT,grace@comp.com,P3
108,Henry Davis,Engineering,2018-05-20,82000.0,NaN,NaN,NaN
109,Ivy Rodriguez,Sales,2022-01-05,71000.0,NaN,NaN,NaN
110,Jack Martinez,IT,2021-03-12,76000.0,NaN,NaN,NaN
111,NaN,NaN,NaT,NaN,Sales,new111@comp.com,P4
112,NaN,NaN,NaT,NaN,HR,new112@comp.com,P1