- merge --> this join based on the columns, index (like a SQL)

- join --> this join based on the index

- concatenation --> stack work (vstack, hstack)

Merge
--

In [6]:
import pandas as pd
import numpy as np

df_info = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'Major': ['Computer Science', 'Engineering', 'History', 'Physics', 'Biology', 'Computer Science', 'Physics', 'Engineering', 'Biology', 'History'],
    'Year': [1, 2, 3, 4, 1, 2, 3, 4, 1, 2]
})

df_grades = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 106, 107, 108, 109, 110, 111],
    'GPA': [3.8, 3.5, 3.1, 3.9, 3.2, 3.6, 3.0, 3.7, 3.4, 3.1],
    'Credits_Completed': [30, 60, 90, 120, 50, 85, 110, 25, 55, 45]
})

df_new_stud = pd.DataFrame({
    'StudentID': [111, 112, 113, 114],
    'Name': ['Kyle', 'Laura', 'Michael', 'Nina'],
    'Major': ['Physics', 'Engineering', 'Computer Science', 'Biology'],
    'Year': [1, 2, 1, 3]
})

In [8]:
df_info

   StudentID     Name             Major  Year
0        101    Alice  Computer Science     1
1        102      Bob       Engineering     2
2        103  Charlie           History     3
3        104    David           Physics     4
4        105      Eve           Biology     1
5        106    Frank  Computer Science     2
6        107    Grace           Physics     3
7        108   Hannah       Engineering     4
8        109      Ivy           Biology     1
9        110     Jack           History     2

In [10]:
df_grades

   StudentID  GPA  Credits_Completed
0        101  3.8                 30
1        102  3.5                 60
2        103  3.1                 90
3        104  3.9                120
4        106  3.2                 50
5        107  3.6                 85
6        108  3.0                110
7        109  3.7                 25
8        110  3.4                 55
9        111  3.1                 45

In [12]:
df_new_stud

   StudentID     Name             Major  Year
0        111     Kyle           Physics     1
1        112    Laura       Engineering     2
2        113  Michael  Computer Science     1
3        114     Nina           Biology     3

In [14]:
pd.merge(df_info,df_grades,how='inner')

   StudentID     Name             Major  Year  GPA  Credits_Completed
0        101    Alice  Computer Science     1  3.8                 30
1        102      Bob       Engineering     2  3.5                 60
2        103  Charlie           History     3  3.1                 90
3        104    David           Physics     4  3.9                120
4        106    Frank  Computer Science     2  3.2                 50
5        107    Grace           Physics     3  3.6                 85
6        108   Hannah       Engineering     4  3.0                110
7        109      Ivy           Biology     1  3.7                 25
8        110     Jack           History     2  3.4                 55

In [16]:
pd.merge(df_info,df_grades,how='left')

   StudentID     Name             Major  Year  GPA  Credits_Completed
0        101    Alice  Computer Science     1  3.8               30.0
1        102      Bob       Engineering     2  3.5               60.0
2        103  Charlie           History     3  3.1               90.0
3        104    David           Physics     4  3.9              120.0
4        105      Eve           Biology     1  NaN                NaN
5        106    Frank  Computer Science     2  3.2               50.0
6        107    Grace           Physics     3  3.6               85.0
7        108   Hannah       Engineering     4  3.0              110.0
8        109      Ivy           Biology     1  3.7               25.0
9        110     Jack           History     2  3.4               55.0

In [18]:
pd.merge(df_info,df_grades,how='right')

   StudentID     Name             Major  Year  GPA  Credits_Completed
0        101    Alice  Computer Science   1.0  3.8                 30
1        102      Bob       Engineering   2.0  3.5                 60
2        103  Charlie           History   3.0  3.1                 90
3        104    David           Physics   4.0  3.9                120
4        106    Frank  Computer Science   2.0  3.2                 50
5        107    Grace           Physics   3.0  3.6                 85
6        108   Hannah       Engineering   4.0  3.0                110
7        109      Ivy           Biology   1.0  3.7                 25
8        110     Jack           History   2.0  3.4                 55
9        111      NaN               NaN   NaN  3.1                 45

In [20]:
pd.merge(df_info,df_grades,how='outer')

    StudentID     Name             Major  Year  GPA  Credits_Completed
0         101    Alice  Computer Science   1.0  3.8               30.0
1         102      Bob       Engineering   2.0  3.5               60.0
2         103  Charlie           History   3.0  3.1               90.0
3         104    David           Physics   4.0  3.9              120.0
4         105      Eve           Biology   1.0  NaN                NaN
5         106    Frank  Computer Science   2.0  3.2               50.0
6         107    Grace           Physics   3.0  3.6               85.0
7         108   Hannah       Engineering   4.0  3.0              110.0
8         109      Ivy           Biology   1.0  3.7               25.0
9         110     Jack           History   2.0  3.4               55.0
10        111      NaN               NaN   NaN  3.1               45.0

In [22]:
pd.merge(df_info,df_grades,how='cross')

,StudentID_x,Name,Major,Year,StudentID_y,GPA,Credits_Completed
0,101,Alice,Computer Science,1,101,3.8,30
1,101,Alice,Computer Science,1,102,3.5,60
2,101,Alice,Computer Science,1,103,3.1,90
3,101,Alice,Computer Science,1,104,3.9,120
4,101,Alice,Computer Science,1,106,3.2,50
...,...,...,...,...,...,...,...
95,110,Jack,History,2,107,3.6,85
96,110,Jack,History,2,108,3.0,110
97,110,Jack,History,2,109,3.7,25
98,110,Jack,History,2,110,3.4,55
99,110,Jack,History,2,111,3.1,45

In [26]:
pd.merge(df_info,df_grades) # no need to mention by default how = inner and on as both tables have common column present in them.

   StudentID     Name             Major  Year  GPA  Credits_Completed
0        101    Alice  Computer Science     1  3.8                 30
1        102      Bob       Engineering     2  3.5                 60
2        103  Charlie           History     3  3.1                 90
3        104    David           Physics     4  3.9                120
4        106    Frank  Computer Science     2  3.2                 50
5        107    Grace           Physics     3  3.6                 85
6        108   Hannah       Engineering     4  3.0                110
7        109      Ivy           Biology     1  3.7                 25
8        110     Jack           History     2  3.4                 55

In [34]:
df_info_index = df_info.set_index("StudentID")
df_grades_index = df_grades.set_index("StudentID")

In [38]:
pd.merge(df_info_index,df_grades_index,on='StudentID',how='inner')

              Name             Major  Year  GPA  Credits_Completed
StudentID
101          Alice  Computer Science     1  3.8                 30
102            Bob       Engineering     2  3.5                 60
103        Charlie           History     3  3.1                 90
104          David           Physics     4  3.9                120
106          Frank  Computer Science     2  3.2                 50
107          Grace           Physics     3  3.6                 85
108         Hannah       Engineering     4  3.0                110
109            Ivy           Biology     1  3.7                 25
110           Jack           History     2  3.4                 55

In [40]:
pd.merge(df_info_index,df_grades_index,on='StudentID',how='right')

              Name             Major  Year  GPA  Credits_Completed
StudentID
101          Alice  Computer Science   1.0  3.8                 30
102            Bob       Engineering   2.0  3.5                 60
103        Charlie           History   3.0  3.1                 90
104          David           Physics   4.0  3.9                120
106          Frank  Computer Science   2.0  3.2                 50
107          Grace           Physics   3.0  3.6                 85
108         Hannah       Engineering   4.0  3.0                110
109            Ivy           Biology   1.0  3.7                 25
110           Jack           History   2.0  3.4                 55
111            NaN               NaN   NaN  3.1                 45

In [42]:
pd.merge(df_info_index,df_grades_index,on='StudentID',how='left')

              Name             Major  Year  GPA  Credits_Completed
StudentID
101          Alice  Computer Science     1  3.8               30.0
102            Bob       Engineering     2  3.5               60.0
103        Charlie           History     3  3.1               90.0
104          David           Physics     4  3.9              120.0
105            Eve           Biology     1  NaN                NaN
106          Frank  Computer Science     2  3.2               50.0
107          Grace           Physics     3  3.6               85.0
108         Hannah       Engineering     4  3.0              110.0
109            Ivy           Biology     1  3.7               25.0
110           Jack           History     2  3.4               55.0

In [44]:
df_info = pd.DataFrame({
    'ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'Major': ['Computer Science', 'Engineering', 'History', 'Physics', 'Biology', 'Computer Science', 'Physics', 'Engineering', 'Biology', 'History'],
    'Year': [1, 2, 3, 4, 1, 2, 3, 4, 1, 2]
})

df_grades = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 106, 107, 108, 109, 110, 111],
    'GPA': [3.8, 3.5, 3.1, 3.9, 3.2, 3.6, 3.0, 3.7, 3.4, 3.1],
    'Credits_Completed': [30, 60, 90, 120, 50, 85, 110, 25, 55, 45]
})

In [46]:
df_info_index1 = df_info.set_index("ID")
df_grades_index1 = df_grades.set_index("StudentID")

In [48]:
pd.merge(df_info_index,df_grades_index,how='inner', right_index=True,left_index=True)

              Name             Major  Year  GPA  Credits_Completed
StudentID
101          Alice  Computer Science     1  3.8                 30
102            Bob       Engineering     2  3.5                 60
103        Charlie           History     3  3.1                 90
104          David           Physics     4  3.9                120
106          Frank  Computer Science     2  3.2                 50
107          Grace           Physics     3  3.6                 85
108         Hannah       Engineering     4  3.0                110
109            Ivy           Biology     1  3.7                 25
110           Jack           History     2  3.4                 55

In [50]:
import pandas as pd
import numpy as np

df_info = pd.DataFrame({
    'ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'Major': ['Computer Science', 'Engineering', 'History', 'Physics', 'Biology', 'Computer Science', 'Physics', 'Engineering', 'Biology', 'History'],
    'Year': [1, 2, 3, 4, 1, 2, 3, 4, 1, 2]
})

df_grades = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 106, 107, 108, 109, 110, 111],
    'GPA': [3.8, 3.5, 3.1, 3.9, 3.2, 3.6, 3.0, 3.7, 3.4, 3.1],
    'Credits_Completed': [30, 60, 90, 120, 50, 85, 110, 25, 55, 45]
})

df_new_stud = pd.DataFrame({
    'StudentID': [111, 112, 113, 114],
    'Name': ['Kyle', 'Laura', 'Michael', 'Nina'],
    'Major': ['Physics', 'Engineering', 'Computer Science', 'Biology'],
    'Year': [1, 2, 1, 3]
})

In [52]:
df_info_index = df_info.set_index("ID")
df_grades_index = df_grades.set_index("StudentID")

In [62]:
pd.merge(df_info, df_grades, how='inner', left_on='ID', right_on='StudentID')

    ID     Name             Major  Year  StudentID  GPA  Credits_Completed
0  101    Alice  Computer Science     1        101  3.8                 30
1  102      Bob       Engineering     2        102  3.5                 60
2  103  Charlie           History     3        103  3.1                 90
3  104    David           Physics     4        104  3.9                120
4  106    Frank  Computer Science     2        106  3.2                 50
5  107    Grace           Physics     3        107  3.6                 85
6  108   Hannah       Engineering     4        108  3.0                110
7  109      Ivy           Biology     1        109  3.7                 25
8  110     Jack           History     2        110  3.4                 55

In [58]:
pd.merge(df_info_index, df_grades_index, how='inner', left_index=True, right_index=True)

        Name             Major  Year  GPA  Credits_Completed
101    Alice  Computer Science     1  3.8                 30
102      Bob       Engineering     2  3.5                 60
103  Charlie           History     3  3.1                 90
104    David           Physics     4  3.9                120
106    Frank  Computer Science     2  3.2                 50
107    Grace           Physics     3  3.6                 85
108   Hannah       Engineering     4  3.0                110
109      Ivy           Biology     1  3.7                 25
110     Jack           History     2  3.4                 55

Note
--

- if the both tables have same column with same data type -> on='common column"

- if the both tables have same index -> right_index=True, left_index=True

- if both tables have different names columns with same records then -> right_on= right_table_column', left_on="left_table_column'

- if the left table has index and right table has column equal then -> left_index=True, right_on='column_name'

Join
---

In [67]:
df_info.join(df_grades)
# Note : if the both tables don't have any common index then uts take default index with range of 0 to N.

    ID     Name             Major  Year  StudentID  GPA  Credits_Completed
0  101    Alice  Computer Science     1        101  3.8                 30
1  102      Bob       Engineering     2        102  3.5                 60
2  103  Charlie           History     3        103  3.1                 90
3  104    David           Physics     4        104  3.9                120
4  105      Eve           Biology     1        106  3.2                 50
5  106    Frank  Computer Science     2        107  3.6                 85
6  107    Grace           Physics     3        108  3.0                110
7  108   Hannah       Engineering     4        109  3.7                 25
8  109      Ivy           Biology     1        110  3.4                 55
9  110     Jack           History     2        111  3.1                 45

In [69]:
df_info_index.join(df_grades)

        Name             Major  Year  StudentID  GPA  Credits_Completed
ID
101    Alice  Computer Science     1        NaN  NaN                NaN
102      Bob       Engineering     2        NaN  NaN                NaN
103  Charlie           History     3        NaN  NaN                NaN
104    David           Physics     4        NaN  NaN                NaN
105      Eve           Biology     1        NaN  NaN                NaN
106    Frank  Computer Science     2        NaN  NaN                NaN
107    Grace           Physics     3        NaN  NaN                NaN
108   Hannah       Engineering     4        NaN  NaN                NaN
109      Ivy           Biology     1        NaN  NaN                NaN
110     Jack           History     2        NaN  NaN                NaN

In [77]:
df_info_index.join(df_grades_index)

        Name             Major  Year  GPA  Credits_Completed
ID
101    Alice  Computer Science     1  3.8               30.0
102      Bob       Engineering     2  3.5               60.0
103  Charlie           History     3  3.1               90.0
104    David           Physics     4  3.9              120.0
105      Eve           Biology     1  NaN                NaN
106    Frank  Computer Science     2  3.2               50.0
107    Grace           Physics     3  3.6               85.0
108   Hannah       Engineering     4  3.0              110.0
109      Ivy           Biology     1  3.7               25.0
110     Jack           History     2  3.4               55.0

In [81]:
df_grades_index

           GPA  Credits_Completed
StudentID
101        3.8                 30
102        3.5                 60
103        3.1                 90
104        3.9                120
106        3.2                 50
107        3.6                 85
108        3.0                110
109        3.7                 25
110        3.4                 55
111        3.1                 45

In [87]:
df_grades.join( df_new_stud.set_index('StudentID'), on='StudentID')

   StudentID  GPA  Credits_Completed  Name    Major  Year
0        101  3.8                 30   NaN      NaN   NaN
1        102  3.5                 60   NaN      NaN   NaN
2        103  3.1                 90   NaN      NaN   NaN
3        104  3.9                120   NaN      NaN   NaN
4        106  3.2                 50   NaN      NaN   NaN
5        107  3.6                 85   NaN      NaN   NaN
6        108  3.0                110   NaN      NaN   NaN
7        109  3.7                 25   NaN      NaN   NaN
8        110  3.4                 55   NaN      NaN   NaN
9        111  3.1                 45  Kyle  Physics   1.0

In [89]:
import pandas as pd
import numpy as np

df_info = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'Major': ['Computer Science', 'Engineering', 'History', 'Physics', 'Biology', 'Computer Science', 'Physics', 'Engineering', 'Biology', 'History'],
    'Year': [1, 2, 3, 4, 1, 2, 3, 4, 1, 2]
})

df_grades = pd.DataFrame({
    'StudentID': [101, 102, 103, 104, 106, 107, 108, 109, 110, 111],
    'GPA': [3.8, 3.5, 3.1, 3.9, 3.2, 3.6, 3.0, 3.7, 3.4, 3.1],
    'Credits_Completed': [30, 60, 90, 120, 50, 85, 110, 25, 55, 45]
})

df_new_stud = pd.DataFrame({
    'StudentID': [111, 112, 113, 114],
    'Name': ['Kyle', 'Laura', 'Michael', 'Nina'],
    'Major': ['Physics', 'Engineering', 'Computer Science', 'Biology'],
    'Year': [1, 2, 1, 3]
})

In [95]:
df_info.join(df_new_stud,on='StudentID',lsuffix='_left',rsuffix='_right')

,StudentID,StudentID_left,Name_left,Major_left,Year_left,StudentID_right,Name_right,Major_right,Year_right
0,101,101,Alice,Computer Science,1,NaN,NaN,NaN,NaN
1,102,102,Bob,Engineering,2,NaN,NaN,NaN,NaN
2,103,103,Charlie,History,3,NaN,NaN,NaN,NaN
3,104,104,David,Physics,4,NaN,NaN,NaN,NaN
4,105,105,Eve,Biology,1,NaN,NaN,NaN,NaN
5,106,106,Frank,Computer Science,2,NaN,NaN,NaN,NaN
6,107,107,Grace,Physics,3,NaN,NaN,NaN,NaN
7,108,108,Hannah,Engineering,4,NaN,NaN,NaN,NaN
8,109,109,Ivy,Biology,1,NaN,NaN,NaN,NaN
9,110,110,Jack,History,2,NaN,NaN,NaN,NaN

In [97]:
df_info.join(df_new_stud,on='StudentID',lsuffix='_left',rsuffix='_right',sort=True)

,StudentID,StudentID_left,Name_left,Major_left,Year_left,StudentID_right,Name_right,Major_right,Year_right
0,101,101,Alice,Computer Science,1,NaN,NaN,NaN,NaN
1,102,102,Bob,Engineering,2,NaN,NaN,NaN,NaN
2,103,103,Charlie,History,3,NaN,NaN,NaN,NaN
3,104,104,David,Physics,4,NaN,NaN,NaN,NaN
4,105,105,Eve,Biology,1,NaN,NaN,NaN,NaN
5,106,106,Frank,Computer Science,2,NaN,NaN,NaN,NaN
6,107,107,Grace,Physics,3,NaN,NaN,NaN,NaN
7,108,108,Hannah,Engineering,4,NaN,NaN,NaN,NaN
8,109,109,Ivy,Biology,1,NaN,NaN,NaN,NaN
9,110,110,Jack,History,2,NaN,NaN,NaN,NaN

In [99]:
df_info.join(df_grades,on='StudentID',lsuffix='_left',rsuffix='_right',sort=True,validate='one_to_one')

# validate : str, optional
#     If specified, checks if join is of specified type.

#     * "one_to_one" or "1:1": check if join keys are unique in both left
#       and right datasets.
#     * "one_to_many" or "1:m": check if join keys are unique in left dataset.
#     * "many_to_one" or "m:1": check if join keys are unique in right dataset.
#     * "many_to_many" or "m:m": allowed, but does not result in checks.

,StudentID,StudentID_left,Name,Major,Year,StudentID_right,GPA,Credits_Completed
0,101,101,Alice,Computer Science,1,NaN,NaN,NaN
1,102,102,Bob,Engineering,2,NaN,NaN,NaN
2,103,103,Charlie,History,3,NaN,NaN,NaN
3,104,104,David,Physics,4,NaN,NaN,NaN
4,105,105,Eve,Biology,1,NaN,NaN,NaN
5,106,106,Frank,Computer Science,2,NaN,NaN,NaN
6,107,107,Grace,Physics,3,NaN,NaN,NaN
7,108,108,Hannah,Engineering,4,NaN,NaN,NaN
8,109,109,Ivy,Biology,1,NaN,NaN,NaN
9,110,110,Jack,History,2,NaN,NaN,NaN

In [101]:
df_info.join(df_grades,on='StudentID',lsuffix='_left',rsuffix='_right',sort=True,validate='one_to_many')

,StudentID,StudentID_left,Name,Major,Year,StudentID_right,GPA,Credits_Completed
0,101,101,Alice,Computer Science,1,NaN,NaN,NaN
1,102,102,Bob,Engineering,2,NaN,NaN,NaN
2,103,103,Charlie,History,3,NaN,NaN,NaN
3,104,104,David,Physics,4,NaN,NaN,NaN
4,105,105,Eve,Biology,1,NaN,NaN,NaN
5,106,106,Frank,Computer Science,2,NaN,NaN,NaN
6,107,107,Grace,Physics,3,NaN,NaN,NaN
7,108,108,Hannah,Engineering,4,NaN,NaN,NaN
8,109,109,Ivy,Biology,1,NaN,NaN,NaN
9,110,110,Jack,History,2,NaN,NaN,NaN

In [103]:
df_info.join(df_grades,on='StudentID',lsuffix='_left',rsuffix='_right',sort=True,validate='many_to_many')

,StudentID,StudentID_left,Name,Major,Year,StudentID_right,GPA,Credits_Completed
0,101,101,Alice,Computer Science,1,NaN,NaN,NaN
1,102,102,Bob,Engineering,2,NaN,NaN,NaN
2,103,103,Charlie,History,3,NaN,NaN,NaN
3,104,104,David,Physics,4,NaN,NaN,NaN
4,105,105,Eve,Biology,1,NaN,NaN,NaN
5,106,106,Frank,Computer Science,2,NaN,NaN,NaN
6,107,107,Grace,Physics,3,NaN,NaN,NaN
7,108,108,Hannah,Engineering,4,NaN,NaN,NaN
8,109,109,Ivy,Biology,1,NaN,NaN,NaN
9,110,110,Jack,History,2,NaN,NaN,NaN

In [105]:
pd.merge(
    df_info,
    df_new_stud,
    how='left',
    on='StudentID',
    suffixes=('', '_new')
)

   StudentID     Name             Major  Year Name_new Major_new  Year_new
0        101    Alice  Computer Science     1      NaN       NaN       NaN
1        102      Bob       Engineering     2      NaN       NaN       NaN
2        103  Charlie           History     3      NaN       NaN       NaN
3        104    David           Physics     4      NaN       NaN       NaN
4        105      Eve           Biology     1      NaN       NaN       NaN
5        106    Frank  Computer Science     2      NaN       NaN       NaN
6        107    Grace           Physics     3      NaN       NaN       NaN
7        108   Hannah       Engineering     4      NaN       NaN       NaN
8        109      Ivy           Biology     1      NaN       NaN       NaN
9        110     Jack           History     2      NaN       NaN       NaN

In [107]:
pd.merge(
    df_info,
    df_grades,
    how='left',
    on='StudentID',
    suffixes=('', '_new')
)

   StudentID     Name             Major  Year  GPA  Credits_Completed
0        101    Alice  Computer Science     1  3.8               30.0
1        102      Bob       Engineering     2  3.5               60.0
2        103  Charlie           History     3  3.1               90.0
3        104    David           Physics     4  3.9              120.0
4        105      Eve           Biology     1  NaN                NaN
5        106    Frank  Computer Science     2  3.2               50.0
6        107    Grace           Physics     3  3.6               85.0
7        108   Hannah       Engineering     4  3.0              110.0
8        109      Ivy           Biology     1  3.7               25.0
9        110     Jack           History     2  3.4               55.0

In [109]:
df_info.join(
    df_grades,
    on='StudentID',
    lsuffix='_left',
    rsuffix='_right',
    sort=True,
    validate='many_to_many'
)

,StudentID,StudentID_left,Name,Major,Year,StudentID_right,GPA,Credits_Completed
0,101,101,Alice,Computer Science,1,NaN,NaN,NaN
1,102,102,Bob,Engineering,2,NaN,NaN,NaN
2,103,103,Charlie,History,3,NaN,NaN,NaN
3,104,104,David,Physics,4,NaN,NaN,NaN
4,105,105,Eve,Biology,1,NaN,NaN,NaN
5,106,106,Frank,Computer Science,2,NaN,NaN,NaN
6,107,107,Grace,Physics,3,NaN,NaN,NaN
7,108,108,Hannah,Engineering,4,NaN,NaN,NaN
8,109,109,Ivy,Biology,1,NaN,NaN,NaN
9,110,110,Jack,History,2,NaN,NaN,NaN

In [111]:
df_info.join(
    df_grades.set_index('StudentID'),
    on='StudentID',
    validate='one_to_one'
)

   StudentID     Name             Major  Year  GPA  Credits_Completed
0        101    Alice  Computer Science     1  3.8               30.0
1        102      Bob       Engineering     2  3.5               60.0
2        103  Charlie           History     3  3.1               90.0
3        104    David           Physics     4  3.9              120.0
4        105      Eve           Biology     1  NaN                NaN
5        106    Frank  Computer Science     2  3.2               50.0
6        107    Grace           Physics     3  3.6               85.0
7        108   Hannah       Engineering     4  3.0              110.0
8        109      Ivy           Biology     1  3.7               25.0
9        110     Jack           History     2  3.4               55.0

In [124]:
df_info.join(
    df_new_stud.set_index('StudentID'),
    on='StudentID',
    how='outer',
    lsuffix='_left',
    rsuffix='_right',
    validate='many_to_many'
)

,StudentID,Name_left,Major_left,Year_left,Name_right,Major_right,Year_right
0.0,101,Alice,Computer Science,1.0,NaN,NaN,NaN
1.0,102,Bob,Engineering,2.0,NaN,NaN,NaN
2.0,103,Charlie,History,3.0,NaN,NaN,NaN
3.0,104,David,Physics,4.0,NaN,NaN,NaN
4.0,105,Eve,Biology,1.0,NaN,NaN,NaN
5.0,106,Frank,Computer Science,2.0,NaN,NaN,NaN
6.0,107,Grace,Physics,3.0,NaN,NaN,NaN
7.0,108,Hannah,Engineering,4.0,NaN,NaN,NaN
8.0,109,Ivy,Biology,1.0,NaN,NaN,NaN
9.0,110,Jack,History,2.0,NaN,NaN,NaN
NaN,111,NaN,NaN,NaN,Kyle,Physics,1.0
NaN,112,NaN,NaN,NaN,Laura,Engineering,2.0
NaN,113,NaN,NaN,NaN,Michael,Computer Science,1.0
NaN,114,NaN,NaN,NaN,Nina,Biology,3.0

Concatenation
---

In [134]:
pd.concat([df_info, df_new_stud], ignore_index=True)

    StudentID     Name             Major  Year
0         101    Alice  Computer Science     1
1         102      Bob       Engineering     2
2         103  Charlie           History     3
3         104    David           Physics     4
4         105      Eve           Biology     1
5         106    Frank  Computer Science     2
6         107    Grace           Physics     3
7         108   Hannah       Engineering     4
8         109      Ivy           Biology     1
9         110     Jack           History     2
10        111     Kyle           Physics     1
11        112    Laura       Engineering     2
12        113  Michael  Computer Science     1
13        114     Nina           Biology     3

In [137]:
# axis = 0
# two are merged from top to bottom

pd.concat([df_info, df_new_stud])

   StudentID     Name             Major  Year
0        101    Alice  Computer Science     1
1        102      Bob       Engineering     2
2        103  Charlie           History     3
3        104    David           Physics     4
4        105      Eve           Biology     1
5        106    Frank  Computer Science     2
6        107    Grace           Physics     3
7        108   Hannah       Engineering     4
8        109      Ivy           Biology     1
9        110     Jack           History     2
0        111     Kyle           Physics     1
1        112    Laura       Engineering     2
2        113  Michael  Computer Science     1
3        114     Nina           Biology     3

In [139]:
pd.concat([df_info, df_new_stud],axis=0,ignore_index=True)

    StudentID     Name             Major  Year
0         101    Alice  Computer Science     1
1         102      Bob       Engineering     2
2         103  Charlie           History     3
3         104    David           Physics     4
4         105      Eve           Biology     1
5         106    Frank  Computer Science     2
6         107    Grace           Physics     3
7         108   Hannah       Engineering     4
8         109      Ivy           Biology     1
9         110     Jack           History     2
10        111     Kyle           Physics     1
11        112    Laura       Engineering     2
12        113  Michael  Computer Science     1
13        114     Nina           Biology     3

In [141]:
pd.concat([df_info, df_new_stud],axis=1)

,StudentID,Name,Major,Year,StudentID,Name,Major,Year
0,101,Alice,Computer Science,1,111.0,Kyle,Physics,1.0
1,102,Bob,Engineering,2,112.0,Laura,Engineering,2.0
2,103,Charlie,History,3,113.0,Michael,Computer Science,1.0
3,104,David,Physics,4,114.0,Nina,Biology,3.0
4,105,Eve,Biology,1,NaN,NaN,NaN,NaN
5,106,Frank,Computer Science,2,NaN,NaN,NaN,NaN
6,107,Grace,Physics,3,NaN,NaN,NaN,NaN
7,108,Hannah,Engineering,4,NaN,NaN,NaN,NaN
8,109,Ivy,Biology,1,NaN,NaN,NaN,NaN
9,110,Jack,History,2,NaN,NaN,NaN,NaN

In [143]:
import pandas as pd

df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 30, 28]
})

df2 = pd.DataFrame({
    'Name': ['David', 'Eva', 'Frank'],
    'Age': [35, 27, 32]
})

In [145]:
pd.concat([df1,df2])

      Name  Age
0    Alice   24
1      Bob   30
2  Charlie   28
0    David   35
1      Eva   27
2    Frank   32

In [147]:
pd.concat([df1,df2],axis=1)

      Name  Age   Name  Age
0    Alice   24  David   35
1      Bob   30    Eva   27
2  Charlie   28  Frank   32

In [149]:
import pandas as pd

df1 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 30, 28]
})

df2 = pd.DataFrame({
    'Director': ['David', 'Eva', 'Frank'],
    'Salary': [35000, 27000, 32000]
})

In [151]:
pd.concat([df1,df2],axis=0)

      Name   Age Director   Salary
0    Alice  24.0      NaN      NaN
1      Bob  30.0      NaN      NaN
2  Charlie  28.0      NaN      NaN
0      NaN   NaN    David  35000.0
1      NaN   NaN      Eva  27000.0
2      NaN   NaN    Frank  32000.0

In [153]:
pd.concat([df1,df2],axis=1)

      Name  Age Director  Salary
0    Alice   24    David   35000
1      Bob   30      Eva   27000
2  Charlie   28    Frank   32000

In [155]:
df3 = pd.concat([df1,df2],axis=1)

In [157]:
df3

      Name  Age Director  Salary
0    Alice   24    David   35000
1      Bob   30      Eva   27000
2  Charlie   28    Frank   32000

Date and Time
--

In [1]:
import pandas as pd

df = pd.DataFrame({
    'Date': [
        '2024-01-01',
        '2024-01-05',
        '2024-01-10',
        '2024-01-15',
        '2024-01-20'
    ]
})

In [3]:
df

         Date
0  2024-01-01
1  2024-01-05
2  2024-01-10
3  2024-01-15
4  2024-01-20

In [5]:
df.dtypes

Date    object
dtype: object

In [7]:
pd.to_datetime(df['Date'])

0   2024-01-01
1   2024-01-05
2   2024-01-10
3   2024-01-15
4   2024-01-20
Name: Date, dtype: datetime64[ns]

In [9]:
df['Date'] = pd.to_datetime(df['Date'])

In [11]:
df

        Date
0 2024-01-01
1 2024-01-05
2 2024-01-10
3 2024-01-15
4 2024-01-20

In [13]:
df['Year'] = df['Date'].dt.year

In [15]:
df

        Date  Year
0 2024-01-01  2024
1 2024-01-05  2024
2 2024-01-10  2024
3 2024-01-15  2024
4 2024-01-20  2024

In [17]:
df['Month'] = df['Date'].dt.month

In [19]:
df

        Date  Year  Month
0 2024-01-01  2024      1
1 2024-01-05  2024      1
2 2024-01-10  2024      1
3 2024-01-15  2024      1
4 2024-01-20  2024      1

In [21]:
df['Day'] = df['Date'].dt.day

In [23]:
df

        Date  Year  Month  Day
0 2024-01-01  2024      1    1
1 2024-01-05  2024      1    5
2 2024-01-10  2024      1   10
3 2024-01-15  2024      1   15
4 2024-01-20  2024      1   20

In [25]:
df['Day Name'] = df['Date'].dt.day_name()

In [27]:
df

        Date  Year  Month  Day   Day Name
0 2024-01-01  2024      1    1     Monday
1 2024-01-05  2024      1    5     Friday
2 2024-01-10  2024      1   10  Wednesday
3 2024-01-15  2024      1   15     Monday
4 2024-01-20  2024      1   20   Saturday

In [41]:
df['Day Week'] = df['Date'].dt.day_of_week
df

        Date  Year  Month  Day   Day Name  Day Week
0 2024-01-01  2024      1    1     Monday         0
1 2024-01-05  2024      1    5     Friday         4
2 2024-01-10  2024      1   10  Wednesday         2
3 2024-01-15  2024      1   15     Monday         0
4 2024-01-20  2024      1   20   Saturday         5

In [43]:
df['Date'].dt.day_of_year

0     1
1     5
2    10
3    15
4    20
Name: Date, dtype: int32

In [33]:
x = df['Date']

In [35]:
x

0   2024-01-01
1   2024-01-05
2   2024-01-10
3   2024-01-15
4   2024-01-20
Name: Date, dtype: datetime64[ns]

In [39]:
x.dt.day_of_week

0    0
1    4
2    2
3    0
4    5
Name: Date, dtype: int32

In [45]:
x.dt.day_of_year

0     1
1     5
2    10
3    15
4    20
Name: Date, dtype: int32

In [47]:
x.dt.daysinmonth

0    31
1    31
2    31
3    31
4    31
Name: Date, dtype: int32

In [49]:
x.dt.is_leap_year

0    True
1    True
2    True
3    True
4    True
Name: Date, dtype: bool

In [55]:
x.dt.days_in_month

0    31
1    31
2    31
3    31
4    31
Name: Date, dtype: int32